services:
  nginx:
    container_name: nginx
    build: srcs/requirements/nginx/Dockerfile
    ports: 
      - "8080:443"
    restart: unless-stopped
    networks:
      - inception
    secrets:
      - key
      - cert

  wordpress:
    container_name: wordpress

networks:
  inception:
    name: inception

secrets:
  cert:
    file: ../secrets/nginx.crt
  key:
    file: ../secrets/nginx.key

volumes:
  wordpress:
    


