services:
  nginx:
    container_name: nginx
    build:
        context: requirements/nginx
        dockerfile: Dockerfile
    ports: 
      - "8080:443"
    restart: on-failure
    networks:
      - inception
    secrets:
      - key
      - cert

networks:
  inception:
    name: inception

secrets:
  cert:
    file: ../secrets/nginx.crt
  key:
    file: ../secrets/nginx.key

volumes:
  wordpress:
    


